import path from "node:path";

import fs from "fs-extra";

import type { ContextMap, Recommendation } from "../types.js";
import { createUnifiedDiff, hasTextChanged, summarizeDiff } from "../utils/diff.js";
import { readJson, writeText } from "../utils/fs.js";
import { log } from "../utils/logger.js";
import { displayPath, hausPath } from "../utils/paths.js";

const STABLE_ID = "generated.project-facts";
const SCHEMA_VERSION = "1";

function makeHeader(pkgVersion: string): string {
  return `<!-- HAUS-MANAGED id=${STABLE_ID} v=${SCHEMA_VERSION} source=@haus-tech/haus-workflow@${pkgVersion} -->`;
}

export function renderProjectFacts(ctx: ContextMap, rec: Recommendation, pkgVersion: string): string {
  const header = makeHeader(pkgVersion);

  const stackEntries = Object.entries(ctx.detectedStacks ?? {});
  const stackLines =
    stackEntries.length > 0
      ? stackEntries
          .map(([stack, files]) => {
            const f = files as string[];
            return `- **${stack}**: ${f.slice(0, 3).join(", ")}${f.length > 3 ? ", …" : ""}`;
          })
          .join("\n")
      : "- none detected";

  const roles = ctx.repoRoles?.length > 0 ? ctx.repoRoles.join(", ") : "unknown";

  const recLines =
    rec.recommended.length > 0
      ? rec.recommended.map((r) => `- \`${r.id}\` (${r.type}) — ${r.reason}`).join("\n")
      : "- none";

  const warningLines = [...(ctx.warnings ?? []), ...(rec.warnings ?? [])];
  const warnSection = warningLines.length > 0 ? warningLines.map((w) => `- ${w}`).join("\n") : "- none";

  const repoName = ctx.repoName ?? path.basename(ctx.root ?? "unknown");

  return `${header}

# Project facts

> Auto-generated by \`haus apply\`. Do not edit — changes will be overwritten on next apply.

**Repo:** ${repoName}
**Package manager:** ${ctx.packageManager ?? "unknown"}
**Roles:** ${roles}

## Detected stacks

${stackLines}

## Recommended context

${recLines}

## Warnings

${warnSection}
`;
}

export async function writeProjectFacts(root: string, pkgVersion: string, dryRun: boolean): Promise<string> {
  const ctx = (await readJson<ContextMap>(hausPath(root, "context-map.json"))) ?? {
    mode: "fast" as const,
    generatedAt: new Date().toISOString(),
    root,
    repoName: path.basename(root),
    packageManager: "unknown" as const,
    repoRoles: [],
    confidence: 0,
    detectedStacks: {},
    dependencies: [],
    securityRisks: [],
    crossRepoHints: [],
    warnings: [],
  };
  const rec = (await readJson<Recommendation>(hausPath(root, "recommendation.json"))) ?? {
    mode: "fast" as const,
    recommended: [],
    skipped: [],
    warnings: [],
    estimatedContextTokens: 0,
    selectedRules: 0,
    skippedRules: 0,
    estimatedTokenReductionPct: 0,
  };

  const destPath = hausPath(root, "project.md");
  const printable = displayPath(root, destPath);
  const next = renderProjectFacts(ctx, rec, pkgVersion);
  const prev = (await fs.pathExists(destPath)) ? await fs.readFile(destPath, "utf8") : "";

  if (dryRun) {
    if (!prev) {
      log(createUnifiedDiff(printable, "", next));
    } else if (hasTextChanged(prev, next)) {
      log(createUnifiedDiff(printable, prev, next));
    } else {
      log(`${printable}: unchanged`);
    }
    return destPath;
  }

  if (hasTextChanged(prev, next) && prev.length > 0) {
    const diffText = createUnifiedDiff(printable, prev, next);
    const summary = summarizeDiff(diffText);
    log(`Overwriting ${printable} (diff +${summary.additions} -${summary.deletions})`);
  }

  await writeText(destPath, next);
  return destPath;
}
